/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.image.editor;

public class App{
    

    App(){

    }
    public static void main(String[] args){
        MainWindow mw = new MainWindow();
    }



}



